### ISSUE TITLE
Is it thread-safe?

### ISSUE THREAD

**Issue by decates** [eealeivan/mixpanel-csharp#14]
Do you know if the implementation used is deliberately thread-safe?
That is to say, can I use the same `MixpanelClient` across different threads (for example in a web app), and be happy that it will behave the way I'd expect?
Thanks.

**Comment by eealeivan** [comment]
Yes, `MixpanelClient` is thread safe and can be used from multiple threads at the same time. 
There is one place which can be potentially have problems. If you provide your own implementation of some methods in [MixpanelConfig](https://github.com/eealeivan/mixpanel-csharp/blob/master/src/Mixpanel/Mixpanel/MixpanelConfig.cs) then you need to be sure that it is thread safe.
