### ISSUE TITLE
[Feature Request] identify and reset not available

### ISSUE THREAD

**Issue by garie** [eealeivan/mixpanel-csharp#19]
Mixpanel has [defined](https://help.mixpanel.com/hc/en-us/articles/115004497803) how you should handle users signing up, logging out, and using another device after sign up. On sign up, you send the `alias` call, which is available in this library. On log out, the `distinct_id` and super properties should be reset via `reset` - this is not available in this library. When a previously signed up user logs in on another device, you should not call alias, which will fail if called a second time, but call `identify`, which is not available in this library.

[identify](https://github.com/mixpanel/mixpanel-swift/blob/c51a8f06aefcce83d9e1d86776a8eafd1cd0be7e/Mixpanel/MixpanelInstance.swift#L760) in swift

[reset](https://github.com/mixpanel/mixpanel-swift/blob/c51a8f06aefcce83d9e1d86776a8eafd1cd0be7e/Mixpanel/MixpanelInstance.swift#L888) in swift

~It doesn't look like either of these make server calls.~
Actually `identify` sends a `$identify` track event

JavaScript
```
4744	+         // send an $identify event any time the distinct_id is changing - logic on the server
4745	+         // will determine whether or not to do anything with it.
4746	+         if (new_distinct_id !== previous_distinct_id) {
4747	+             this.track('$identify', { 'distinct_id': new_distinct_id, '$anon_distinct_id': previous_distinct_id });
4748	+         }
```

**Comment by eealeivan** [comment]
This library handles identity management in a bit different way compared to some other libraries. There is no default randomly generated `DistinctId` and all logic must be done by you. You need to set `DistinctId` explicitly and it is handled as any other special property.

There are two main usage scenarios:

**One `MixpanelClient` instance per multiple users (most probably backend app)**
In this case there is no much sense setting `DistinctId` via super properties. You rather should add `DistinctId` to message itself or use an override method that accepts `DistinctId` as a parameter.

**One `MixpanelClient` instance per one user (most probably client app)**
Setting `DistinctId` via super properties simplifies the usage of the library. But you can set super properties only one time when creating `MixpanelClient` instance. So if you want to handle the change of `DistinctId` you will need to create a new instance of client with updated `DistinctId` value.
