### ISSUE TITLE
How to set browser specific & other sets of property?

### ISSUE THREAD

**Issue by ravimakwana3012** [eealeivan/mixpanel-csharp#23]
Hi,

We have started using the latest version of library in our new project and had few questions.

We are using mixpanel JavaScript implementation in our old project and we have noticed that there are few properties which are captured by mixpanel itself from browser when JavaScript was loaded in client side.

List of properties:
1. Browser
2. Browser Version
3. Current URL
4. Device ID

I have not seen all those properties as part of library package.

Can you include these if not there?

Apart from this, What to do to capture Screen Height, Screen Width & OS?

**Comment by eealeivan** [comment]
Hi,

This library was build with the idea that it can run everywhere (backend server, phone app etc.) so there is no built-in functionality for browser specific stuff.

You can add all of this properties yourself to each message or by specifying super properties during the initialization.

How to get all these values is really dependent on the platform that you are using.
