### ISSUE TITLE
Passing "Ignore_Alias" to the PeopleDelete action

### ISSUE THREAD

**Issue by andrewbeattie180** [eealeivan/mixpanel-csharp#25]
Would it be possible to include the bool "ignore_alias" parameter as an optional parameter in the PeopleDelete calls as per the Mixpanel docs? 

_If you have duplicate profiles, use property $ignore_alias set to true so that you don't delete the original profile when trying to delete the duplicate (as they pass in the alias as the distinct_id)._

**Comment by eealeivan** [comment]
This is now available in new version of the library https://www.nuget.org/packages/mixpanel-csharp/6.0.0#release-body-tab
