### ISSUE TITLE
WebProxy

### ISSUE THREAD

**Issue by ChrisIsJustADev** [eealeivan/mixpanel-csharp#27]
Hi,

I would like to add a Proxy / configuration to the MixPanelClient.
How can I do that?

BR
Chris

**Comment by eealeivan** [comment]
Hi!

You can provide your own implementation of HTTP POST functionality as described here https://github.com/eealeivan/mixpanel-csharp/wiki/Configuration#http-post-method

As you can see the default implementation is very straightforward https://github.com/eealeivan/mixpanel-csharp/blob/master/src/Mixpanel/Mixpanel/DefaultHttpClient.cs
