### ISSUE TITLE
Strong-name sign the NuGet package

### ISSUE THREAD

**Issue by brinkdinges** [eealeivan/mixpanel-csharp#29]
I've just spent three days trying to include unsigned NuGet packages in our own internal NuGet packages. But it looks like it can't be done. We are stuck on .NET Framework 4.8 for now, so strong names are important.

Would it be possible for you to strong-name sign your DLL? That would make things so much easier. It only takes two steps:
1: Create a key pair: https://docs.microsoft.com/en-us/dotnet/standard/assembly/create-public-private-key-pair
2: Check a box in Visual Studio: https://docs.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name

Thanks so much,
Peter

**Comment by brinkdinges** [comment]
@eealeivan Thanks for adding strong-name signing so quickly! I had no idea until I just checked your commit history. Do you know when v6 will appear on NuGet?

**Comment by eealeivan** [comment]
I still want to add few new features. Hopefully I will be able to release a new version in few weeks.

**Comment by eealeivan** [comment]
A new version https://www.nuget.org/packages/mixpanel-csharp/6.0.0#release-body-tab which supports strong name signing is now available!
