### ISSUE TITLE
Seems the library doesn't support $insert_id

### ISSUE THREAD

**Issue by roman-ianchenko** [eealeivan/mixpanel-csharp#31]
Hi, seems the library doesn't support $insert_id, or I've not found the way to pass it into the events.

The solution architect suggested it is mandatory when these APIs are used:
https://developer.mixpanel.com/reference/import-events
https://developer.mixpanel.com/reference/track-event

Could you please advise how to pass it?

**Comment by eealeivan** [comment]
Hi,

You can just pass $insert_id together with other properties:
```
var client = new MixpanelClient("6972694d809c7390676a138834f8c890");
var message = client.TrackTest("Played Song", new Dictionary<string, object> {
	{"$insert_id", "5d958f87-542d-4c10-9422-0ed75893dc81"},
	{MixpanelProperty.DistinctId, "john.doe@gmail.com"},
	{"app_version", "1.1.34.694.gac68a2b3"},
	{"song_id", "0wwPcA6wtMf6HUMpIRdeP7"},
});
```
