### ISSUE TITLE
Nuget package is out of date

### ISSUE THREAD

**Issue by jamiepenney** [eealeivan/mixpanel-csharp#5]
Hi,

The nuget package hasn't been updated with the latest changes - I wanted to be able to use the IP address settings in MixpanelConfig but they're not in 2.1.0.

Great library btw, you've done a really good job of documenting it!

Cheers,
Jamie

**Comment by eealeivan** [comment]
Hi,

New version is published to NuGet https://www.nuget.org/packages/mixpanel-csharp/3.0.0
