### ISSUE TITLE
Track request is not being successful

### ISSUE THREAD

**Issue by xth1** [eealeivan/mixpanel-csharp#9]
I am using the version 4.0.1 on a Xamarin project and I am using a valid mixpanel token.
On my latest tests today none of the tracking requests is being successful ( I added a debug for the `Track` method).
Any hint about that?

**Comment by eealeivan** [comment]
Hi,

I will check it and get back here.

**Comment by Bhagwat-23** [comment]
Hello eealeivan,

First of all thanks for providing such a helpful APIs for mixpanel , you have really done a great job 👍 Kudos :) 
I've one question , have you written any APIs to consume or export event data and user data for client side?
I can see some export data official APIs are available in mixpanel , are you planning to integrate it with .NET?

**Comment by eealeivan** [comment]
@Bhagwat-23 Hi, thanks! I haven't touched export API yet. At the moment I don't have a plans to integrate it to .NET too :(

**Comment by eealeivan** [comment]
@xth1 Hi, sorry that my reply took so long. I just tested it with simple Xamarin app and it worked OK. 

So I just created Blank Android App in VS 2017 and used all default settings. Then I added one button to the main view and used this code:

```csharp
[Activity(Label = "Mixpanel.Xamarin", MainLauncher = true)]
public class MainActivity : Activity
{
    private MixpanelClient mixpanelClient;

    protected override void OnCreate(Bundle savedInstanceState)
    {
        base.OnCreate(savedInstanceState);

        // Set our view from the "main" layout resource
        SetContentView(Resource.Layout.Main);

        mixpanelClient = new MixpanelClient("TOKEN");
        MixpanelConfig.Global.SerializeJsonFn = JsonConvert.SerializeObject;

        FindViewById<Button>(Resource.Id.btnMixpanel).Click += BtnMixpnaelClick;
    }

    private void BtnMixpnaelClick(object sender, EventArgs e)
    {
        mixpanelClient.Track("Test", new { Timespan = DateTime.UtcNow.ToString("G") });
    }
}
```

If it still silently fails for you then maybe you can try enable logging https://github.com/eealeivan/mixpanel-csharp/wiki/Configuration#error-logging
